# Config file for automatic testing at travis-ci.org

sudo: false
language: python
python: "3.6"

before_install:
  - pip install poetry
  - pip install tox

install:
  - poetry install

script:
  - tox

before_cache:
  - rm -rf $HOME/.cache/pip/log

cache:
  directories:
    - $HOME/.cache/pip
